### ISSUE TITLE
Need to update the php file

### ISSUE THREAD

**Issue by Worper1997** [binaryage/firelogger.php#2]
Error:

 FireLogger for PHP (v0.2) works best with FireLogger extension of version 0.7. You are currently using extension v0.8. Please upgrade your Firefox extension

Maybe this will be a better idea:
in firelogger.php line 306
change 
if (FireLogger::$clientVersion!=FireLogger::$recommendedClientVersion) {
to 
if (FireLogger::$clientVersion<FireLogger::$recommendedClientVersion) {

**Comment by darwin** [comment]
yup :-) I would rather update wording of that message. I'd like to have matching version numbers. To notify people about the version mismatch.

**Comment by darwin** [comment]
bump version to 0.3, updated recommended version to 0.9, closed by e8bde455754e731c690449105a5e9b936ea1aaf6
