### ISSUE TITLE
Missing class names

### ISSUE THREAD

**Issue by dg** [binaryage/firelogger.php#4]
FireLogger::pickle($object) drops class names (and members visibility, but it does not matter). Class names should be visible on both panels: http://screencast.com/t/NDdmYjQz

**Comment by darwin** [comment]
JSON serializer needs to encode this information somehow, you are welcome to add this feature into pickle function:
http://github.com/darwin/firelogger.php/blob/master/firelogger.php#L56

**Comment by dg** [comment]
Patch is here: http://github.com/dg/firelogger.php/commit/ed451da0e7307f6686e19918b64d2ad74db5d98d

It uses special field __class##

**Comment by darwin** [comment]
thanks merged here:
http://github.com/darwin/firelogger.php/commit/ed451da0e7307f6686e19918b64d2ad74db5d98d

closing, but it would be nice if you also added line into test.php which demonstrates the feature

**Comment by dg** [comment]
Sorry, I forgot ;) Here: http://github.com/dg/firelogger.php/commit/0f7ffb276a12b5eb7bf19fcd449969fb8b9f8a85
