### ISSUE TITLE
„Undefined“ variables

### ISSUE THREAD

**Issue by dg** [binaryage/firelogger.php#5]
Expansions generates unexpected „undefined“ variables: http://screencast.com/t/NWJjYTZlM

(Firefox 3.6.8 + Firebug 1.5.4)

**Comment by darwin** [comment]
yes, this is bug on firebug's side, try some javascript JSON object in firebug's console, it also prints =undefined for its members. 

this is fixed in some later Firebug

**Comment by darwin** [comment]
I guess FireLogger is broken in Firebug 1.6 betas right now. I will fix it soon (or at least when final Firebug 1.6 is released)

**Comment by darwin** [comment]
this should be fixed in http://github.com/darwin/firelogger/commit/867600d2257bd7694ff3b672ab4a846928da6a37
