### ISSUE TITLE
Není vidět soubor a řádka, kde vzniká výjimka

### ISSUE THREAD

**Issue by dg** [binaryage/firelogger.php#8]
Argumenty předané jako pathname & lineno jsou sice rozkliknutelné přes datum a čas, ale nejsou vidět. Tím se ztrácí informace o tom, na kterém řádku a ve kterém souboru vznikla výjimka. Nevím, jestli to chceš nějakým způsobem řešit na straně FireLoggeru, nebo jestli doplnit 'message' o tyto údaje?

**Comment by darwin** [comment]
Muzes kliknout pravym na ten timestamp (radek) a dat "Inspect in DOM tab", tam uvidis lineno a pathname.

**Comment by darwin** [comment]
fixed: http://github.com/darwin/firelogger/commit/68738ba0c68d1b9e8d6d47a4731decf2159602e0
